import { useState, useRef, useEffect, useCallback } from 'react';
import { BACKEND } from '@/lib/api';

interface DeMarkChartProps {
  symbol: string;
  height?: number;
  timeframe?: 'daily' | 'weekly';
  showBB?: boolean;
  fullscreen?: boolean;
  onRequestFullscreen?: () => void;
}

/**
 * Renders a DeMark OHLC chart as a server-rendered PNG image.
 * The chart is generated by the Python backend using matplotlib with
 * OHLC bars, Bollinger Bands, and DeMark annotations (setup/countdown).
 *
 * Supports an optional fullscreen modal with zoom/pan capability.
 */
export default function LightweightChart({
  symbol,
  height = 400,
  timeframe = 'daily',
  showBB = false,
  fullscreen = false,
  onRequestFullscreen,
}: DeMarkChartProps) {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  const imgSrc = `${BACKEND}/api/chart/${symbol}/${timeframe}?show_bb=${showBB}&t=${Date.now()}`;

  if (fullscreen) {
    return (
      <FullscreenChartView
        imgSrc={imgSrc}
        symbol={symbol}
        timeframe={timeframe}
      />
    );
  }

  return (
    <div className="relative w-full" style={{ height }}>
      {loading && !error && (
        <div className="absolute inset-0 flex items-center justify-center z-10">
          <div className="flex items-center gap-2 text-signal-text-muted text-xs">
            <div className="w-4 h-4 border-2 border-signal-green/30 border-t-signal-green rounded-full animate-spin" />
            Loading chart...
          </div>
        </div>
      )}
      {error && (
        <div className="absolute inset-0 flex items-center justify-center z-10">
          <div className="text-signal-text-muted text-xs">
            No chart data for {symbol}
          </div>
        </div>
      )}
      <img
        src={imgSrc}
        alt={`${symbol} ${timeframe} DeMark chart`}
        data-testid={`chart-${symbol}`}
        className="w-full h-full object-contain"
        style={{ display: error ? 'none' : 'block' }}
        onLoad={() => setLoading(false)}
        onError={() => { setLoading(false); setError(true); }}
      />
    </div>
  );
}


/* ─── Fullscreen zoom/pan viewer ──────────────────────────────────── */

function FullscreenChartView({
  imgSrc,
  symbol,
  timeframe,
}: {
  imgSrc: string;
  symbol: string;
  timeframe: string;
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const imgRef = useRef<HTMLImageElement>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  // zoom / pan state
  const [scale, setScale] = useState(1);
  const [translate, setTranslate] = useState({ x: 0, y: 0 });
  const dragRef = useRef({ dragging: false, startX: 0, startY: 0, startTx: 0, startTy: 0 });

  // Zoom with mouse wheel
  const handleWheel = useCallback((e: WheelEvent) => {
    e.preventDefault();
    setScale(prev => {
      const next = prev - e.deltaY * 0.001;
      return Math.min(Math.max(next, 0.5), 5);
    });
  }, []);

  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    el.addEventListener('wheel', handleWheel, { passive: false });
    return () => el.removeEventListener('wheel', handleWheel);
  }, [handleWheel]);

  // Pan with mouse drag
  const handleMouseDown = useCallback((e: React.MouseEvent) => {
    if (scale <= 1) return; // only pan when zoomed in
    dragRef.current = {
      dragging: true,
      startX: e.clientX,
      startY: e.clientY,
      startTx: translate.x,
      startTy: translate.y,
    };
  }, [scale, translate]);

  const handleMouseMove = useCallback((e: React.MouseEvent) => {
    if (!dragRef.current.dragging) return;
    const dx = e.clientX - dragRef.current.startX;
    const dy = e.clientY - dragRef.current.startY;
    setTranslate({
      x: dragRef.current.startTx + dx,
      y: dragRef.current.startTy + dy,
    });
  }, []);

  const handleMouseUp = useCallback(() => {
    dragRef.current.dragging = false;
  }, []);

  // Touch pinch-zoom support
  const touchRef = useRef({ dist: 0, scale0: 1 });

  const handleTouchStart = useCallback((e: React.TouchEvent) => {
    if (e.touches.length === 2) {
      const dx = e.touches[0].clientX - e.touches[1].clientX;
      const dy = e.touches[0].clientY - e.touches[1].clientY;
      touchRef.current = { dist: Math.hypot(dx, dy), scale0: scale };
    } else if (e.touches.length === 1 && scale > 1) {
      dragRef.current = {
        dragging: true,
        startX: e.touches[0].clientX,
        startY: e.touches[0].clientY,
        startTx: translate.x,
        startTy: translate.y,
      };
    }
  }, [scale, translate]);

  const handleTouchMove = useCallback((e: React.TouchEvent) => {
    if (e.touches.length === 2) {
      const dx = e.touches[0].clientX - e.touches[1].clientX;
      const dy = e.touches[0].clientY - e.touches[1].clientY;
      const dist = Math.hypot(dx, dy);
      const ratio = dist / touchRef.current.dist;
      setScale(Math.min(Math.max(touchRef.current.scale0 * ratio, 0.5), 5));
    } else if (e.touches.length === 1 && dragRef.current.dragging) {
      const dx2 = e.touches[0].clientX - dragRef.current.startX;
      const dy2 = e.touches[0].clientY - dragRef.current.startY;
      setTranslate({
        x: dragRef.current.startTx + dx2,
        y: dragRef.current.startTy + dy2,
      });
    }
  }, []);

  const handleTouchEnd = useCallback(() => {
    dragRef.current.dragging = false;
  }, []);

  const resetView = useCallback(() => {
    setScale(1);
    setTranslate({ x: 0, y: 0 });
  }, []);

  const zoomIn = useCallback(() => {
    setScale(prev => Math.min(prev + 0.5, 5));
  }, []);

  const zoomOut = useCallback(() => {
    setScale(prev => {
      const next = Math.max(prev - 0.5, 0.5);
      if (next <= 1) setTranslate({ x: 0, y: 0 });
      return next;
    });
  }, []);

  return (
    <div
      ref={containerRef}
      className="relative w-full h-full overflow-hidden select-none"
      style={{ cursor: scale > 1 ? 'grab' : 'default' }}
      onMouseDown={handleMouseDown}
      onMouseMove={handleMouseMove}
      onMouseUp={handleMouseUp}
      onMouseLeave={handleMouseUp}
      onTouchStart={handleTouchStart}
      onTouchMove={handleTouchMove}
      onTouchEnd={handleTouchEnd}
      data-testid="fullscreen-chart-viewer"
    >
      {/* Zoom controls */}
      <div className="absolute top-3 right-3 z-20 flex items-center gap-1">
        <button
          onClick={zoomOut}
          data-testid="zoom-out"
          className="w-8 h-8 flex items-center justify-center rounded bg-signal-surface/80 border border-signal-border text-signal-text-secondary hover:text-signal-text text-sm font-bold transition-colors backdrop-blur-sm"
        >
          −
        </button>
        <button
          onClick={resetView}
          data-testid="zoom-reset"
          className="h-8 px-2 flex items-center justify-center rounded bg-signal-surface/80 border border-signal-border text-signal-text-secondary hover:text-signal-text text-[10px] font-medium tabular-nums transition-colors backdrop-blur-sm"
        >
          {Math.round(scale * 100)}%
        </button>
        <button
          onClick={zoomIn}
          data-testid="zoom-in"
          className="w-8 h-8 flex items-center justify-center rounded bg-signal-surface/80 border border-signal-border text-signal-text-secondary hover:text-signal-text text-sm font-bold transition-colors backdrop-blur-sm"
        >
          +
        </button>
      </div>

      {/* Loading / error states */}
      {loading && !error && (
        <div className="absolute inset-0 flex items-center justify-center z-10">
          <div className="flex items-center gap-2 text-signal-text-muted text-xs">
            <div className="w-4 h-4 border-2 border-signal-green/30 border-t-signal-green rounded-full animate-spin" />
            Loading chart...
          </div>
        </div>
      )}
      {error && (
        <div className="absolute inset-0 flex items-center justify-center z-10">
          <div className="text-signal-text-muted text-xs">
            No chart data for {symbol}
          </div>
        </div>
      )}

      {/* Chart image with zoom/pan transform */}
      <img
        ref={imgRef}
        src={imgSrc}
        alt={`${symbol} ${timeframe} DeMark chart (fullscreen)`}
        data-testid={`fullscreen-chart-img-${symbol}`}
        className="w-full h-full object-contain transition-transform duration-75"
        style={{
          display: error ? 'none' : 'block',
          transform: `translate(${translate.x}px, ${translate.y}px) scale(${scale})`,
          transformOrigin: 'center center',
        }}
        draggable={false}
        onLoad={() => setLoading(false)}
        onError={() => { setLoading(false); setError(true); }}
      />
    </div>
  );
}
