import { useState } from 'react';

interface DeMarkChartProps {
  symbol: string;
  height?: number;
  timeframe?: 'daily' | 'weekly';
  showBB?: boolean;
}

/**
 * Renders a DeMark OHLC chart as a server-rendered PNG image.
 * The chart is generated by the Python backend using matplotlib with
 * OHLC bars, Bollinger Bands, and DeMark annotations (setup/countdown).
 */
export default function LightweightChart({
  symbol,
  height = 400,
  timeframe = 'daily',
  showBB = false,
}: DeMarkChartProps) {
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(false);

  const imgSrc = `/api/chart/${symbol}/${timeframe}?show_bb=${showBB}&t=${Date.now()}`;

  return (
    <div className="relative w-full" style={{ height }}>
      {loading && !error && (
        <div className="absolute inset-0 flex items-center justify-center z-10">
          <div className="flex items-center gap-2 text-signal-text-muted text-xs">
            <div className="w-4 h-4 border-2 border-signal-green/30 border-t-signal-green rounded-full animate-spin" />
            Loading chart...
          </div>
        </div>
      )}
      {error && (
        <div className="absolute inset-0 flex items-center justify-center z-10">
          <div className="text-signal-text-muted text-xs">
            No chart data for {symbol}
          </div>
        </div>
      )}
      <img
        src={imgSrc}
        alt={`${symbol} ${timeframe} DeMark chart`}
        data-testid={`chart-${symbol}`}
        className="w-full h-full object-contain"
        style={{ display: error ? 'none' : 'block' }}
        onLoad={() => setLoading(false)}
        onError={() => { setLoading(false); setError(true); }}
      />
    </div>
  );
}
